restBundle\Entity\Place:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
            - Type: string
        address:
            - NotBlank: ~
            - Type: string
restBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        firstname:
            - NotBlank: ~
            - Type: string
        email:
            - NotBlank: ~
            - Type: string
restBundle\Entity\userPocket:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        accountNumber:
            - NotBlank: ~
            - Type: string
        transactionPhone:
            - NotBlank: ~
            - Type: string
        solde:
            - NotBlank: ~
            - Type: integer
        userName:
            - NotBlank: ~
            - Type: string
        userPass:
            - NotBlank: ~
            - Type: string
restBundle\Entity\codeRecharge:
    constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        montant:
            - NotBlank: ~
            - Type: integer
        code:
            - NotBlank: ~
            - Type: string
        destinataire:
            - NotBlank: ~
            - Type: string
        isUsed:
            - NotBlank: ~
            - Type: boolean
restBundle\Entity\appRouter:
    constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        operateur:
            - NotBlank: ~
            - Type: string
        token:
            - NotBlank: ~
            - Type: string
        tel:
            - NotBlank: ~
            - Type: string
        pays:
            - NotBlank: ~
            - Type: boolean
estBundle\Entity\verifCode:
    constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        tel:
            - NotBlank: ~
            - Type: string
        code:
            - NotBlank: ~
            - Type: string
restBundle\Entity\smsFromMaxiSms:
    constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        to:
            - NotBlank: ~
            - Type: string
        from:
            - NotBlank: ~
            - Type: string
        body:
            - NotBlank: ~
            - Type: string
