<?php

namespace restB\restBundle\Repository;

/**
 * codeRechargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class codeRechargeRepository extends \Doctrine\ORM\EntityRepository
{
}
