<?php

namespace restB\restBundle\Repository;

/**
 * codeToExecuteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class codeToExecuteRepository extends \Doctrine\ORM\EntityRepository
{
}
