<?php

namespace restB\restBundle\Repository;

/**
 * gsmOperatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gsmOperatorRepository extends \Doctrine\ORM\EntityRepository
{
}
