<?php

namespace restB\restBundle\Repository;

/**
 * userPocketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userPocketRepository extends \Doctrine\ORM\EntityRepository
{
}
