<?php

namespace restB\restBundle\Repository;
use restB\restBundle\Entity\userPocket;

/**
 * userPocketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userPocketRepository extends \Doctrine\ORM\EntityRepository
{
    public function resetSolde($tphone, $value){

            //$qB = $this->createQueryBuilder('p');
            $qB = $this->getEntityManager()->createQueryBuilder();
            $qB ->update('restBundle:userPocket', 'p')
                ->set('p.solde', '?1')
                ->where('p.transactionPhone = ?2')
                ->setParameter(1, $value)
                ->setParameter(2, $tphone);

            return $qB->getQuery()->execute();

    }
    public function resetConnexionStatut($tphone, $value){

        //$qB = $this->createQueryBuilder('p');
        $qB = $this->getEntityManager()->createQueryBuilder();
        $qB ->update('restBundle:userPocket', 'p')
            ->set('p.isOneline', '?1')
            ->where('p.transactionPhone = ?2')
            ->setParameter(1, $value)
            ->setParameter(2, $tphone);

        return $qB->getQuery()->execute();

    }
    public function refreshFtoken($tphone, $pass,$token){

        //$qB = $this->createQueryBuilder('p');
        $qB = $this->getEntityManager()->createQueryBuilder();
        $qB ->update('restBundle:userPocket', 'p')
            ->set('p.fbtoken', '?1')
            ->where('p.transactionPhone = ?2')
            ->where('p.pass = ?3')
            ->setParameter(1, $token)
            ->setParameter(2, $tphone)
        ->setParameter(3, $pass);

        return $qB->getQuery()->execute();

    }
}
