<?php

namespace restB\restBundle\Repository;

/**
 * ussdArgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ussdArgRepository extends \Doctrine\ORM\EntityRepository
{
}
