<?php

namespace restB\restBundle\Repository;

/**
 * ussdResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ussdResponseRepository extends \Doctrine\ORM\EntityRepository
{
}
